package org.requal;

import org.junit.Test;
import org.hamcrest.Matcher;

import java.util.List;
import java.util.Arrays;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertThat;


/**
 * Created by IntelliJ IDEA.
 * User: mburnett
 * Date: Apr 30, 2010
 * Time: 7:09:14 PM
 * To change this template use File | Settings | File Templates.
 */
public class JarWalkerTest {

    @Test
    public void shouldWalkHamcrestJar() {
        JarWalker walker = new JarWalker("hamcrest-all-1.2.jar");
        List<String> classNames = walker.listClassNames();
        assertThat(classNames, is(expectedClasses));
    }

    List<String> expectedClasses = Arrays.asList(
            "org.hamcrest.BaseDescription",
            "org.hamcrest.BaseMatcher",
            "org.hamcrest.CoreMatchers",
            "org.hamcrest.CustomMatcher",
            "org.hamcrest.CustomTypeSafeMatcher",
            "org.hamcrest.Description$NullDescription",
            "org.hamcrest.Description",
            "org.hamcrest.DiagnosingMatcher",
            "org.hamcrest.Factory",
            "org.hamcrest.FeatureMatcher",
            "org.hamcrest.Matcher",
            "org.hamcrest.MatcherAssert",
            "org.hamcrest.SelfDescribing",
            "org.hamcrest.StringDescription",
            "org.hamcrest.TypeSafeDiagnosingMatcher",
            "org.hamcrest.TypeSafeMatcher",
            "org.hamcrest.core.AllOf",
            "org.hamcrest.core.AnyOf",
            "org.hamcrest.core.CombinableMatcher",
            "org.hamcrest.core.DescribedAs",
            "org.hamcrest.core.Every",
            "org.hamcrest.core.Is",
            "org.hamcrest.core.IsAnything",
            "org.hamcrest.core.IsCollectionContaining",
            "org.hamcrest.core.IsEqual",
            "org.hamcrest.core.IsInstanceOf",
            "org.hamcrest.core.IsNot",
            "org.hamcrest.core.IsNull",
            "org.hamcrest.core.IsSame",
            "org.hamcrest.core.ShortcutCombination",
            "org.hamcrest.core.StringContains",
            "org.hamcrest.core.StringEndsWith",
            "org.hamcrest.core.StringStartsWith",
            "org.hamcrest.core.SubstringMatcher",
            "org.hamcrest.internal.ArrayIterator",
            "org.hamcrest.internal.ReflectiveTypeFinder",
            "org.hamcrest.internal.SelfDescribingValue",
            "org.hamcrest.internal.SelfDescribingValueIterator",
            "org.hamcrest.Matchers",
            "org.hamcrest.beans.HasProperty",
            "org.hamcrest.beans.HasPropertyWithValue",
            "org.hamcrest.beans.PropertyUtil",
            "org.hamcrest.beans.SamePropertyValuesAs$PropertyMatcher",
            "org.hamcrest.beans.SamePropertyValuesAs",
            "org.hamcrest.collection.IsArray",
            "org.hamcrest.collection.IsArrayContaining",
            "org.hamcrest.collection.IsArrayContainingInAnyOrder",
            "org.hamcrest.collection.IsArrayContainingInOrder",
            "org.hamcrest.collection.IsArrayWithSize",
            "org.hamcrest.collection.IsCollectionWithSize",
            "org.hamcrest.collection.IsEmptyCollection",
            "org.hamcrest.collection.IsEmptyIterable",
            "org.hamcrest.collection.IsIn",
            "org.hamcrest.collection.IsIterableContainingInAnyOrder$1",
            "org.hamcrest.collection.IsIterableContainingInAnyOrder$Matching",
            "org.hamcrest.collection.IsIterableContainingInAnyOrder",
            "org.hamcrest.collection.IsIterableContainingInOrder$1",
            "org.hamcrest.collection.IsIterableContainingInOrder$MatchSeries",
            "org.hamcrest.collection.IsIterableContainingInOrder",
            "org.hamcrest.collection.IsIterableWithSize",
            "org.hamcrest.collection.IsMapContaining",
            "org.hamcrest.collection.IsMapContainingKey",
            "org.hamcrest.collection.IsMapContainingValue",
            "org.hamcrest.number.IsCloseTo",
            "org.hamcrest.number.OrderingComparison",
            "org.hamcrest.object.HasToString",
            "org.hamcrest.object.IsCompatibleType",
            "org.hamcrest.object.IsEventFrom",
            "org.hamcrest.text.IsEmptyString",
            "org.hamcrest.text.IsEqualIgnoringCase",
            "org.hamcrest.text.IsEqualIgnoringWhiteSpace",
            "org.hamcrest.text.StringContainsInOrder",
            "org.hamcrest.xml.HasXPath",
            "org.hamcrest.generator.EasyMock2FactoryWriter",
            "org.hamcrest.generator.FactoryMethod$Parameter",
            "org.hamcrest.generator.FactoryMethod",
            "org.hamcrest.generator.FactoryWriter",
            "org.hamcrest.generator.HamcrestFactoryWriter",
            "org.hamcrest.generator.QDox",
            "org.hamcrest.generator.QDoxFactoryReader$1",
            "org.hamcrest.generator.QDoxFactoryReader",
            "org.hamcrest.generator.QuickReferenceWriter",
            "org.hamcrest.generator.ReflectiveFactoryReader$1",
            "org.hamcrest.generator.ReflectiveFactoryReader",
            "org.hamcrest.generator.SugarConfiguration",
            "org.hamcrest.generator.SugarGenerator",
            "org.hamcrest.generator.config.XmlConfigurator$1",
            "org.hamcrest.generator.config.XmlConfigurator",
            "org.hamcrest.generator.qdox.JavaDocBuilder$1",
            "org.hamcrest.generator.qdox.JavaDocBuilder",
            "org.hamcrest.generator.qdox.Searcher",
            "org.hamcrest.generator.qdox.ant.AbstractQdoxTask",
            "org.hamcrest.generator.qdox.directorywalker.DirectoryScanner$1",
            "org.hamcrest.generator.qdox.directorywalker.DirectoryScanner",
            "org.hamcrest.generator.qdox.directorywalker.FileVisitor",
            "org.hamcrest.generator.qdox.directorywalker.Filter",
            "org.hamcrest.generator.qdox.directorywalker.SuffixFilter",
            "org.hamcrest.generator.qdox.junit.APITestCase$1",
            "org.hamcrest.generator.qdox.junit.APITestCase",
            "org.hamcrest.generator.qdox.model.AbstractInheritableJavaEntity",
            "org.hamcrest.generator.qdox.model.AbstractJavaEntity",
            "org.hamcrest.generator.qdox.model.BeanProperty",
            "org.hamcrest.generator.qdox.model.ClassLibrary",
            "org.hamcrest.generator.qdox.model.DefaultDocletTag",
            "org.hamcrest.generator.qdox.model.DefaultDocletTagFactory",
            "org.hamcrest.generator.qdox.model.DocletTag",
            "org.hamcrest.generator.qdox.model.DocletTagFactory",
            "org.hamcrest.generator.qdox.model.IndentBuffer",
            "org.hamcrest.generator.qdox.model.JavaClass",
            "org.hamcrest.generator.qdox.model.JavaClassCache",
            "org.hamcrest.generator.qdox.model.JavaClassParent",
            "org.hamcrest.generator.qdox.model.JavaField",
            "org.hamcrest.generator.qdox.model.JavaMethod",
            "org.hamcrest.generator.qdox.model.JavaParameter",
            "org.hamcrest.generator.qdox.model.JavaSource",
            "org.hamcrest.generator.qdox.model.Member",
            "org.hamcrest.generator.qdox.model.ModelBuilder",
            "org.hamcrest.generator.qdox.model.Type",
            "org.hamcrest.generator.qdox.model.util.OrderedMap$Entry",
            "org.hamcrest.generator.qdox.model.util.OrderedMap$OrderedSet",
            "org.hamcrest.generator.qdox.model.util.OrderedMap",
            "org.hamcrest.generator.qdox.model.util.TagParser",
            "org.hamcrest.generator.qdox.parser.Builder",
            "org.hamcrest.generator.qdox.parser.Lexer",
            "org.hamcrest.generator.qdox.parser.ParseException",
            "org.hamcrest.generator.qdox.parser.impl.JFlexLexer",
            "org.hamcrest.generator.qdox.parser.impl.Parser$1",
            "org.hamcrest.generator.qdox.parser.impl.Parser$Value",
            "org.hamcrest.generator.qdox.parser.impl.Parser",
            "org.hamcrest.generator.qdox.parser.structs.ClassDef",
            "org.hamcrest.generator.qdox.parser.structs.FieldDef",
            "org.hamcrest.generator.qdox.parser.structs.LocatedDef",
            "org.hamcrest.generator.qdox.parser.structs.MethodDef",
            "org.hamcrest.generator.qdox.parser.structs.TagDef",
            "org.hamcrest.generator.qdox.parser.structs.TypeDef",
            "org.hamcrest.generator.qdox.tools.QDoxTester$1",
            "org.hamcrest.generator.qdox.tools.QDoxTester$ConsoleReporter",
            "org.hamcrest.generator.qdox.tools.QDoxTester$Reporter",
            "org.hamcrest.generator.qdox.tools.QDoxTester",
            "org.hamcrest.EasyMock2Matchers",
            "org.hamcrest.JMock1Matchers",
            "org.hamcrest.JavaLangMatcherAssert",
            "org.hamcrest.integration.EasyMock2Adapter",
            "org.hamcrest.integration.JMock1Adapter");


}
